sudo: false
dist: trusty

language: c

addons:
  apt:
    packages:
    - libgmp-dev

env:
- ARGS="--resolver=lts-6"
- ARGS="--resolver=lts-9"
- ARGS="--resolver=nightly"

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
- stack --version
- stack $ARGS setup --no-terminal

script:
- stack $ARGS init
- stack $ARGS build --haddock --no-haddock-deps
- stack $ARGS sdist

cache:
  directories:
  - $HOME/.stack
